[package]
name = "evidenceangel"
description = "Library and executables to work with EvidenceAngel evidence packages (*.evp)."
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "evidenceangel-cli"
path = "src/evidenceangel-cli/main.rs"
required-features = [ "cli" ]

[features]
cli = [
    "dep:clap",
    "dep:pretty_env_logger",
]

[dependencies]
base64 = "0.22.1"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.4", features = [ "derive" ], optional = true }
getset = "0.1.2"
infer = "0.15.0"
log = "0.4.21"
pretty_env_logger = { version = "0.5.0", optional = true }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
sha256 = "1.5.0"
thiserror = "1.0.59"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "serde"] }
zip = "1.1.4"
