# Recommended: Specify your app ID *OR* your base resource path for more robust icon loading
app_id = "uk.hpkns.EvidenceAngel"
base_resource_path = "/uk/hpkns/EvidenceAngel/"

# List of icon names you found (shipped with this crate)
# Note: the file ending `-symbolic.svg` isn't part of the icon name.
icons = ["menu", "plus", "lightbulb", "cross-large", "folder-open-filled", "delete-filled"]
icon_folder = "icons"
